steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo2/myimage2', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo2/myimage2']
timeout: 3600s
