steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/ptb-docker-repo/ptbimage', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/ptb-docker-repo/ptbimage']
timeout: 3600s
